dcfemtech/hackforgood-waba-map

site.js

Refactoring the styles for the bikelanes and buffers so they can be standardized and reused.
/cc @sara4844 @shannonturner

Sets bike lane style and buffer to variables for reuse

---

site.js

Separated code for color fix from geolocator code from issue2_location
@shannonturner @alulsh

Fix colors - refactored from issue2_location branch

---

site.js

fixes #16. Also, we don't have to keep adding to the done function every time we add a new geojson file :-)

fixed load issue with multiple geojason files

---

.gitignore
index.html
site.js
styles.css

added geocoder control (location search) and moved css into its own file

---

site.js

Displays the address a user searched for in the geocoder when they click on a marker.

Displays address from geocoder on marker click

---

index.html
site.js

Added distances of 500ft, 1000ft, 2500ft, and 1 mile to drop down. 1 mile default. @alulsh

Switch to drop down

---

site.js

Rename file, fix 404

---

site.js

Bai Fairfax County :hocho:

---

site.js

Remove fairfax county again

---

site.js

Refactors code:
* use lower camel case for variable and function names
* use single quotes instead of double quotes
* use `data` instead of `e` for callbacks
* remove white space
* reorder code

Refactor and code style changes

---

site.js

Added code comments to the Javascript file to better guide a new contributor on how the code works and on the syntax expected by the Mapbox SDK

Added code comments

---

.eslintrc
.gitignore
CONTRIBUTING.md
README.md
package.json

* Initial package.json file
* Adds eslint for code linting, with eslintrc config file
* Modifies .gitignore to ignore npm-debug.log files
Right now eslint is checking all JavaScript files (`*.js`) in the main directory of the repo - if we move to a dedicated `js` or `app` directory then we will need to update the command.
/cc @NealHumphrey

Adds npm support and eslint

---

site.js

changed all the double quotes in site.js to single quotes

Changed to single quotes

---

index.html
site.js
styles.css

Added draggable menu/infoBox functionality, tweaked positioning (to fit start positions for menu, modal error box and infoBox along left side), tweaked styles for consistent look (WABA green) on branch "menuTweaks".

added draggable menus, positioning, consistent styles

---

index.html

Removed the location box on the bottom left corner that displayed latitude and longitude.

Removed Location Box

---

.travis.yml
site.js

Setting up Travis for automated tests (`npm test`) per https://github.com/dcfemtech/hackforgood-waba-map/issues/79.

Adds .travis.yml for Travis CI

---

site.js

Small bit of code got left in after the UI element was removed.

Remove location updater

---

site.js

* Makes variable names camelCase instead of capitalized
* Adds a few extra spaces between functions to be more consistent

Code style changes to be more JavaScript-friendly

---

index.html

* Removes unused code - commented out lines and mapbox-gl-js-directions plugin
* Changes code style of `tr`s and `td`s to be easier to read
* Fixes Fairfax County UI menu so the buffers load 🎉 
I also added the buffer circles for the "all" regions selector even though these don't work yet - we will need to update the JavaScript in site.js for this to work.

Fixes for index.html

---

site.js

Creating a PR for this - looks great @mdelcambre!
Refs https://github.com/dcfemtech/hackforgood-waba-map/issues/116.

Change color and opacity for #116

---

site.js

* Wraps JavaScript in [an IIFE to namespace code](http://stackoverflow.com/a/8228308)
* Switch to relative URLs for data files on the same domain instead of absolute URLs on a different domain (`raw.githubusercontent.com`)

Refactors JavaScript

---

index.html
styles.css

This PR refactors the current HTML & CSS on the `front-end-changes` branch.
* Adds consistent indentation to `index.html`
* Improves comments in `index.html`
* Removes unused classes and ids from `styles.css`
* I also changes some CSS from `styles.css` to be global (e.g. all `img` elements) and converted them to individual IDs
/cc @hareno44

Refactors index.html and styles.css
